// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"
)

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE id = $1
)
`

func (q *Queries) CategoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryNameExists = `-- name: CategoryNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE name = $1
      AND id <> $2
)
`

type CategoryNameExistsParams struct {
	Name       string
	ExcludedID int64
}

func (q *Queries) CategoryNameExists(ctx context.Context, arg CategoryNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryNameExists, arg.Name, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    description
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    name,
    description,
    created_at,
    updated_at
`

type CreateCategoryParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getCategory = `-- name: GetCategory :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM categories
ORDER BY id ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $1,
    description = $2,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $3
RETURNING
    id,
    name,
    description,
    created_at,
    updated_at
`

type UpdateCategoryParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Description, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
