// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkouts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCheckouts = `-- name: CountCheckouts :one
SELECT count(*)::bigint
FROM checkouts
`

func (q *Queries) CountCheckouts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckouts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countItemCheckouts = `-- name: CountItemCheckouts :one
SELECT count(*)::bigint
FROM checkouts
WHERE item_id = $1
`

func (q *Queries) CountItemCheckouts(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countItemCheckouts, itemID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCheckout = `-- name: CreateCheckout :one
INSERT INTO checkouts (
    item_id,
    borrower_user_id,
    created_by_user_id,
    due_at,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
`

type CreateCheckoutParams struct {
	ItemID          int64
	BorrowerUserID  int64
	CreatedByUserID int64
	DueAt           pgtype.Timestamptz
	Notes           string
}

func (q *Queries) CreateCheckout(ctx context.Context, arg CreateCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, createCheckout,
		arg.ItemID,
		arg.BorrowerUserID,
		arg.CreatedByUserID,
		arg.DueAt,
		arg.Notes,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BorrowerUserID,
		&i.CreatedByUserID,
		&i.ReturnedToUserID,
		&i.CheckedOutAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.Notes,
	)
	return i, err
}

const getCheckout = `-- name: GetCheckout :one
SELECT
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
FROM checkouts
WHERE id = $1
`

func (q *Queries) GetCheckout(ctx context.Context, id int64) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckout, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BorrowerUserID,
		&i.CreatedByUserID,
		&i.ReturnedToUserID,
		&i.CheckedOutAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.Notes,
	)
	return i, err
}

const getCheckoutBorrowerForShare = `-- name: GetCheckoutBorrowerForShare :one
SELECT
    id,
    is_active
FROM users
WHERE id = $1
FOR SHARE
`

type GetCheckoutBorrowerForShareRow struct {
	ID       int64
	IsActive bool
}

func (q *Queries) GetCheckoutBorrowerForShare(ctx context.Context, id int64) (GetCheckoutBorrowerForShareRow, error) {
	row := q.db.QueryRow(ctx, getCheckoutBorrowerForShare, id)
	var i GetCheckoutBorrowerForShareRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const getCheckoutForUpdate = `-- name: GetCheckoutForUpdate :one
SELECT
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
FROM checkouts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCheckoutForUpdate(ctx context.Context, id int64) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutForUpdate, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BorrowerUserID,
		&i.CreatedByUserID,
		&i.ReturnedToUserID,
		&i.CheckedOutAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.Notes,
	)
	return i, err
}

const getItemForStatusUpdate = `-- name: GetItemForStatusUpdate :one
SELECT
    id,
    status
FROM items
WHERE id = $1
FOR UPDATE
`

type GetItemForStatusUpdateRow struct {
	ID     int64
	Status string
}

func (q *Queries) GetItemForStatusUpdate(ctx context.Context, id int64) (GetItemForStatusUpdateRow, error) {
	row := q.db.QueryRow(ctx, getItemForStatusUpdate, id)
	var i GetItemForStatusUpdateRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getTransactionTimestamp = `-- name: GetTransactionTimestamp :one
SELECT transaction_timestamp()::timestamptz
`

func (q *Queries) GetTransactionTimestamp(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getTransactionTimestamp)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const listCheckouts = `-- name: ListCheckouts :many
SELECT
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
FROM checkouts
ORDER BY id DESC
LIMIT $2
OFFSET $1
`

type ListCheckoutsParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListCheckouts(ctx context.Context, arg ListCheckoutsParams) ([]Checkout, error) {
	rows, err := q.db.Query(ctx, listCheckouts, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkout{}
	for rows.Next() {
		var i Checkout
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.BorrowerUserID,
			&i.CreatedByUserID,
			&i.ReturnedToUserID,
			&i.CheckedOutAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCheckouts = `-- name: ListItemCheckouts :many
SELECT
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
FROM checkouts
WHERE item_id = $1
ORDER BY id DESC
LIMIT $3
OFFSET $2
`

type ListItemCheckoutsParams struct {
	ItemID     int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListItemCheckouts(ctx context.Context, arg ListItemCheckoutsParams) ([]Checkout, error) {
	rows, err := q.db.Query(ctx, listItemCheckouts, arg.ItemID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkout{}
	for rows.Next() {
		var i Checkout
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.BorrowerUserID,
			&i.CreatedByUserID,
			&i.ReturnedToUserID,
			&i.CheckedOutAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec
INSERT INTO audit_events (
    actor_user_id,
    action,
    entity_type,
    entity_identifier,
    request_id,
    before_data,
    after_data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5::text, ''),
    $6,
    $7
)
`

type RecordAuditEventParams struct {
	ActorUserID      *int64
	Action           string
	EntityType       string
	EntityIdentifier string
	RequestID        string
	BeforeData       []byte
	AfterData        []byte
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordAuditEvent,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityIdentifier,
		arg.RequestID,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const recordItemStatusHistory = `-- name: RecordItemStatusHistory :exec
INSERT INTO item_status_history (
    item_id,
    changed_by_user_id,
    previous_status,
    new_status,
    reason,
    source_type,
    source_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type RecordItemStatusHistoryParams struct {
	ItemID          int64
	ChangedByUserID *int64
	PreviousStatus  *string
	NewStatus       string
	Reason          *string
	SourceType      *string
	SourceID        *int64
}

func (q *Queries) RecordItemStatusHistory(ctx context.Context, arg RecordItemStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, recordItemStatusHistory,
		arg.ItemID,
		arg.ChangedByUserID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
		arg.SourceType,
		arg.SourceID,
	)
	return err
}

const returnCheckout = `-- name: ReturnCheckout :one
UPDATE checkouts
SET
    returned_at = GREATEST(statement_timestamp(), checked_out_at + INTERVAL '1 microsecond'),
    returned_to_user_id = $1
WHERE id = $2
  AND returned_at IS NULL
RETURNING
    id,
    item_id,
    borrower_user_id,
    created_by_user_id,
    returned_to_user_id,
    checked_out_at,
    due_at,
    returned_at,
    notes
`

type ReturnCheckoutParams struct {
	ReturnedToUserID *int64
	ID               int64
}

func (q *Queries) ReturnCheckout(ctx context.Context, arg ReturnCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, returnCheckout, arg.ReturnedToUserID, arg.ID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BorrowerUserID,
		&i.CreatedByUserID,
		&i.ReturnedToUserID,
		&i.CheckedOutAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.Notes,
	)
	return i, err
}

const setItemWorkflowStatus = `-- name: SetItemWorkflowStatus :one
UPDATE items
SET
    status = $1,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $2
  AND status = $3
RETURNING id
`

type SetItemWorkflowStatusParams struct {
	NewStatus      string
	ID             int64
	ExpectedStatus string
}

func (q *Queries) SetItemWorkflowStatus(ctx context.Context, arg SetItemWorkflowStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, setItemWorkflowStatus, arg.NewStatus, arg.ID, arg.ExpectedStatus)
	var id int64
	err := row.Scan(&id)
	return id, err
}
