// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
)

const assetTagExists = `-- name: AssetTagExists :one
SELECT EXISTS (
    SELECT 1
    FROM items
    WHERE asset_tag = $1
      AND id <> $2
)
`

type AssetTagExistsParams struct {
	AssetTag   string
	ExcludedID int64
}

func (q *Queries) AssetTagExists(ctx context.Context, arg AssetTagExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, assetTagExists, arg.AssetTag, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    category_id,
    asset_tag,
    name,
    description,
    serial_number
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    category_id,
    location_id,
    asset_tag,
    name,
    description,
    serial_number,
    status,
    created_at,
    updated_at
`

type CreateItemParams struct {
	CategoryID   *int64
	AssetTag     string
	Name         string
	Description  string
	SerialNumber *string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.CategoryID,
		arg.AssetTag,
		arg.Name,
		arg.Description,
		arg.SerialNumber,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LocationID,
		&i.AssetTag,
		&i.Name,
		&i.Description,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM items
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteItem, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getItem = `-- name: GetItem :one
SELECT
    id,
    category_id,
    location_id,
    asset_tag,
    name,
    description,
    serial_number,
    status,
    created_at,
    updated_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LocationID,
		&i.AssetTag,
		&i.Name,
		&i.Description,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT
    id,
    category_id,
    location_id,
    asset_tag,
    name,
    description,
    serial_number,
    status,
    created_at,
    updated_at
FROM items
ORDER BY id ASC
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.LocationID,
			&i.AssetTag,
			&i.Name,
			&i.Description,
			&i.SerialNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
    category_id = $1,
    asset_tag = $2,
    name = $3,
    description = $4,
    serial_number = $5,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $6
RETURNING
    id,
    category_id,
    location_id,
    asset_tag,
    name,
    description,
    serial_number,
    status,
    created_at,
    updated_at
`

type UpdateItemParams struct {
	CategoryID   *int64
	AssetTag     string
	Name         string
	Description  string
	SerialNumber *string
	ID           int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.CategoryID,
		arg.AssetTag,
		arg.Name,
		arg.Description,
		arg.SerialNumber,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LocationID,
		&i.AssetTag,
		&i.Name,
		&i.Description,
		&i.SerialNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
