// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID               int64
	ActorUserID      *int64
	Action           string
	EntityType       string
	EntityIdentifier string
	RequestID        *string
	SourceIp         *netip.Addr
	BeforeData       []byte
	AfterData        []byte
	CreatedAt        pgtype.Timestamptz
}

type Category struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Checkout struct {
	ID               int64
	ItemID           int64
	BorrowerUserID   int64
	CreatedByUserID  int64
	ReturnedToUserID *int64
	CheckedOutAt     pgtype.Timestamptz
	DueAt            pgtype.Timestamptz
	ReturnedAt       pgtype.Timestamptz
	Notes            string
}

type ConditionReport struct {
	ID                  int64
	ItemID              int64
	ReportedByUserID    int64
	CheckoutID          *int64
	MaintenanceRecordID *int64
	ReportStage         string
	ConditionRating     string
	Notes               string
	CreatedAt           pgtype.Timestamptz
}

type Item struct {
	ID           int64
	CategoryID   *int64
	LocationID   *int64
	AssetTag     string
	Name         string
	Description  string
	SerialNumber *string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ItemStatusHistory struct {
	ID              int64
	ItemID          int64
	ChangedByUserID *int64
	PreviousStatus  *string
	NewStatus       string
	Reason          *string
	SourceType      *string
	SourceID        *int64
	ChangedAt       pgtype.Timestamptz
}

type Location struct {
	ID               int64
	ParentLocationID *int64
	Code             string
	Name             string
	Description      string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MaintenanceRecord struct {
	ID               int64
	ItemID           int64
	OpenedByUserID   int64
	AssignedToUserID *int64
	Status           string
	Reason           string
	Description      string
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Reservation struct {
	ID                int64
	ItemID            int64
	RequestedByUserID int64
	StartsAt          pgtype.Timestamptz
	EndsAt            pgtype.Timestamptz
	Status            string
	Notes             string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID              int64
	Username        string
	Email           *string
	DisplayName     string
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	IdentityIssuer  *string
	ExternalSubject *string
	Role            string
}
