// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AssetTagExists(ctx context.Context, arg AssetTagExistsParams) (bool, error)
	CategoryExists(ctx context.Context, id int64) (bool, error)
	CategoryNameExists(ctx context.Context, arg CategoryNameExistsParams) (bool, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) (int64, error)
	DeleteItem(ctx context.Context, id int64) (int64, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListItems(ctx context.Context) ([]Item, error)
	ListUsers(ctx context.Context, isActive *bool) ([]User, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserEmailExists(ctx context.Context, arg UserEmailExistsParams) (bool, error)
	UsernameExists(ctx context.Context, arg UsernameExistsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
