// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AssetTagExists(ctx context.Context, arg AssetTagExistsParams) (bool, error)
	CategoryExists(ctx context.Context, id int64) (bool, error)
	CategoryNameExists(ctx context.Context, arg CategoryNameExistsParams) (bool, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteCategory(ctx context.Context, id int64) (int64, error)
	DeleteItem(ctx context.Context, id int64) (int64, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListItems(ctx context.Context) ([]Item, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
