// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    display_name,
    role,
    identity_issuer,
    external_subject
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
`

type CreateUserParams struct {
	Username        string
	Email           *string
	DisplayName     string
	Role            string
	IdentityIssuer  *string
	ExternalSubject *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.IdentityIssuer,
		arg.ExternalSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
FROM users
WHERE identity_issuer = $1
  AND external_subject = $2
`

type GetUserByExternalIdentityParams struct {
	IdentityIssuer  *string
	ExternalSubject *string
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.IdentityIssuer, arg.ExternalSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const linkUserExternalIdentity = `-- name: LinkUserExternalIdentity :one
UPDATE users
SET
    identity_issuer = $1,
    external_subject = $2,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $3
  AND identity_issuer IS NULL
  AND external_subject IS NULL
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
`

type LinkUserExternalIdentityParams struct {
	IdentityIssuer  *string
	ExternalSubject *string
	ID              int64
}

func (q *Queries) LinkUserExternalIdentity(ctx context.Context, arg LinkUserExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, linkUserExternalIdentity, arg.IdentityIssuer, arg.ExternalSubject, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
FROM users
WHERE $1::boolean IS NULL
   OR is_active = $1
ORDER BY id ASC
`

func (q *Queries) ListUsers(ctx context.Context, isActive *bool) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityIssuer,
			&i.ExternalSubject,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagedUser = `-- name: UpdateManagedUser :one
UPDATE users
SET
    username = $1,
    email = $2,
    display_name = $3,
    role = $4,
    is_active = $5,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $6
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject,
    role
`

type UpdateManagedUserParams struct {
	Username    string
	Email       *string
	DisplayName string
	Role        string
	IsActive    bool
	ID          int64
}

func (q *Queries) UpdateManagedUser(ctx context.Context, arg UpdateManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateManagedUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
		&i.Role,
	)
	return i, err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email IS NOT NULL
      AND lower(btrim(email)) = lower(btrim($1))
      AND id <> $2
)
`

type UserEmailExistsParams struct {
	Email      string
	ExcludedID int64
}

func (q *Queries) UserEmailExists(ctx context.Context, arg UserEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExists, arg.Email, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(btrim(username)) = lower(btrim($1))
      AND id <> $2
)
`

type UsernameExistsParams struct {
	Username   string
	ExcludedID int64
}

func (q *Queries) UsernameExists(ctx context.Context, arg UsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, arg.Username, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
