// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    display_name
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
`

type CreateUserParams struct {
	Username    string
	Email       *string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const createUserWithExternalIdentity = `-- name: CreateUserWithExternalIdentity :one
INSERT INTO users (
    username,
    email,
    display_name,
    identity_issuer,
    external_subject
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
`

type CreateUserWithExternalIdentityParams struct {
	Username        string
	Email           *string
	DisplayName     string
	IdentityIssuer  *string
	ExternalSubject *string
}

func (q *Queries) CreateUserWithExternalIdentity(ctx context.Context, arg CreateUserWithExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithExternalIdentity,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.IdentityIssuer,
		arg.ExternalSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
FROM users
WHERE identity_issuer = $1
  AND external_subject = $2
`

type GetUserByExternalIdentityParams struct {
	IdentityIssuer  *string
	ExternalSubject *string
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.IdentityIssuer, arg.ExternalSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
FROM users
WHERE $1::boolean IS NULL
   OR is_active = $1
ORDER BY id ASC
`

func (q *Queries) ListUsers(ctx context.Context, isActive *bool) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityIssuer,
			&i.ExternalSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET
    is_active = $1,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $2
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
`

type SetUserActiveParams struct {
	IsActive bool
	ID       int64
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.IsActive, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = $1,
    email = $2,
    display_name = $3,
    updated_at = GREATEST(statement_timestamp(), updated_at + INTERVAL '1 microsecond')
WHERE id = $4
RETURNING
    id,
    username,
    email,
    display_name,
    is_active,
    created_at,
    updated_at,
    identity_issuer,
    external_subject
`

type UpdateUserParams struct {
	Username    string
	Email       *string
	DisplayName string
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityIssuer,
		&i.ExternalSubject,
	)
	return i, err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email IS NOT NULL
      AND lower(btrim(email)) = lower(btrim($1))
      AND id <> $2
)
`

type UserEmailExistsParams struct {
	Email      string
	ExcludedID int64
}

func (q *Queries) UserEmailExists(ctx context.Context, arg UserEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExists, arg.Email, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(btrim(username)) = lower(btrim($1))
      AND id <> $2
)
`

type UsernameExistsParams struct {
	Username   string
	ExcludedID int64
}

func (q *Queries) UsernameExists(ctx context.Context, arg UsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, arg.Username, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
